/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as ApiWalletsRouteImport } from './routes/api.wallets'
import { Route as ApiRoomsRouteImport } from './routes/api.rooms'
import { Route as ApiPaymentLinksRouteImport } from './routes/api.payment-links'
import { Route as ApiBookingsRouteImport } from './routes/api.bookings'
import { Route as ApiAvailabilityRouteImport } from './routes/api.availability'
import { Route as ApiAmenitiesRouteImport } from './routes/api.amenities'
import { Route as ApiRoomsRoomIdRouteImport } from './routes/api.rooms.$roomId'

const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RoomsRoute,
} as any)
const ApiWalletsRoute = ApiWalletsRouteImport.update({
  id: '/api/wallets',
  path: '/api/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoute = ApiRoomsRouteImport.update({
  id: '/api/rooms',
  path: '/api/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentLinksRoute = ApiPaymentLinksRouteImport.update({
  id: '/api/payment-links',
  path: '/api/payment-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvailabilityRoute = ApiAvailabilityRouteImport.update({
  id: '/api/availability',
  path: '/api/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAmenitiesRoute = ApiAmenitiesRouteImport.update({
  id: '/api/amenities',
  path: '/api/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomIdRoute = ApiRoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ApiRoomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/api/amenities': typeof ApiAmenitiesRoute
  '/api/availability': typeof ApiAvailabilityRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/payment-links': typeof ApiPaymentLinksRoute
  '/api/rooms': typeof ApiRoomsRouteWithChildren
  '/api/wallets': typeof ApiWalletsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/rooms/$roomId': typeof ApiRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/amenities': typeof ApiAmenitiesRoute
  '/api/availability': typeof ApiAvailabilityRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/payment-links': typeof ApiPaymentLinksRoute
  '/api/rooms': typeof ApiRoomsRouteWithChildren
  '/api/wallets': typeof ApiWalletsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms': typeof RoomsIndexRoute
  '/api/rooms/$roomId': typeof ApiRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/api/amenities': typeof ApiAmenitiesRoute
  '/api/availability': typeof ApiAvailabilityRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/payment-links': typeof ApiPaymentLinksRoute
  '/api/rooms': typeof ApiRoomsRouteWithChildren
  '/api/wallets': typeof ApiWalletsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/rooms/$roomId': typeof ApiRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/rooms'
    | '/api/amenities'
    | '/api/availability'
    | '/api/bookings'
    | '/api/payment-links'
    | '/api/rooms'
    | '/api/wallets'
    | '/rooms/$roomId'
    | '/rooms/'
    | '/api/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/api/amenities'
    | '/api/availability'
    | '/api/bookings'
    | '/api/payment-links'
    | '/api/rooms'
    | '/api/wallets'
    | '/rooms/$roomId'
    | '/rooms'
    | '/api/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/rooms'
    | '/api/amenities'
    | '/api/availability'
    | '/api/bookings'
    | '/api/payment-links'
    | '/api/rooms'
    | '/api/wallets'
    | '/rooms/$roomId'
    | '/rooms/'
    | '/api/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  ApiAmenitiesRoute: typeof ApiAmenitiesRoute
  ApiAvailabilityRoute: typeof ApiAvailabilityRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiPaymentLinksRoute: typeof ApiPaymentLinksRoute
  ApiRoomsRoute: typeof ApiRoomsRouteWithChildren
  ApiWalletsRoute: typeof ApiWalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/api/wallets': {
      id: '/api/wallets'
      path: '/api/wallets'
      fullPath: '/api/wallets'
      preLoaderRoute: typeof ApiWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms': {
      id: '/api/rooms'
      path: '/api/rooms'
      fullPath: '/api/rooms'
      preLoaderRoute: typeof ApiRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-links': {
      id: '/api/payment-links'
      path: '/api/payment-links'
      fullPath: '/api/payment-links'
      preLoaderRoute: typeof ApiPaymentLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/availability': {
      id: '/api/availability'
      path: '/api/availability'
      fullPath: '/api/availability'
      preLoaderRoute: typeof ApiAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/amenities': {
      id: '/api/amenities'
      path: '/api/amenities'
      fullPath: '/api/amenities'
      preLoaderRoute: typeof ApiAmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId': {
      id: '/api/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/api/rooms/$roomId'
      preLoaderRoute: typeof ApiRoomsRoomIdRouteImport
      parentRoute: typeof ApiRoomsRoute
    }
  }
}

interface RoomsRouteChildren {
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

interface ApiRoomsRouteChildren {
  ApiRoomsRoomIdRoute: typeof ApiRoomsRoomIdRoute
}

const ApiRoomsRouteChildren: ApiRoomsRouteChildren = {
  ApiRoomsRoomIdRoute: ApiRoomsRoomIdRoute,
}

const ApiRoomsRouteWithChildren = ApiRoomsRoute._addFileChildren(
  ApiRoomsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  RoomsRoute: RoomsRouteWithChildren,
  ApiAmenitiesRoute: ApiAmenitiesRoute,
  ApiAvailabilityRoute: ApiAvailabilityRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiPaymentLinksRoute: ApiPaymentLinksRoute,
  ApiRoomsRoute: ApiRoomsRouteWithChildren,
  ApiWalletsRoute: ApiWalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
